language: python
python:
  - 3.6
  - 3.7
  - 3.8
install:
  - echo "install start"
  - pip install poetry
  - poetry install
  - echo "install end"
script:
  - echo "script start"
  - sh tests/pytest.sh
  - flake8 cointanalysis
  - echo "script end"
after_success:
  - codecov
